// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/leilao.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeilaoService_ParticiparLeilao_FullMethodName = "/leilao.LeilaoService/ParticiparLeilao"
)

// LeilaoServiceClient is the client API for LeilaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeilaoServiceClient interface {
	ParticiparLeilao(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MensagemLance, AtualizacaoLeilao], error)
}

type leilaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeilaoServiceClient(cc grpc.ClientConnInterface) LeilaoServiceClient {
	return &leilaoServiceClient{cc}
}

func (c *leilaoServiceClient) ParticiparLeilao(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MensagemLance, AtualizacaoLeilao], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeilaoService_ServiceDesc.Streams[0], LeilaoService_ParticiparLeilao_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MensagemLance, AtualizacaoLeilao]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeilaoService_ParticiparLeilaoClient = grpc.BidiStreamingClient[MensagemLance, AtualizacaoLeilao]

// LeilaoServiceServer is the server API for LeilaoService service.
// All implementations must embed UnimplementedLeilaoServiceServer
// for forward compatibility.
type LeilaoServiceServer interface {
	ParticiparLeilao(grpc.BidiStreamingServer[MensagemLance, AtualizacaoLeilao]) error
	mustEmbedUnimplementedLeilaoServiceServer()
}

// UnimplementedLeilaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeilaoServiceServer struct{}

func (UnimplementedLeilaoServiceServer) ParticiparLeilao(grpc.BidiStreamingServer[MensagemLance, AtualizacaoLeilao]) error {
	return status.Error(codes.Unimplemented, "method ParticiparLeilao not implemented")
}
func (UnimplementedLeilaoServiceServer) mustEmbedUnimplementedLeilaoServiceServer() {}
func (UnimplementedLeilaoServiceServer) testEmbeddedByValue()                       {}

// UnsafeLeilaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeilaoServiceServer will
// result in compilation errors.
type UnsafeLeilaoServiceServer interface {
	mustEmbedUnimplementedLeilaoServiceServer()
}

func RegisterLeilaoServiceServer(s grpc.ServiceRegistrar, srv LeilaoServiceServer) {
	// If the following call panics, it indicates UnimplementedLeilaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeilaoService_ServiceDesc, srv)
}

func _LeilaoService_ParticiparLeilao_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LeilaoServiceServer).ParticiparLeilao(&grpc.GenericServerStream[MensagemLance, AtualizacaoLeilao]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeilaoService_ParticiparLeilaoServer = grpc.BidiStreamingServer[MensagemLance, AtualizacaoLeilao]

// LeilaoService_ServiceDesc is the grpc.ServiceDesc for LeilaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeilaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leilao.LeilaoService",
	HandlerType: (*LeilaoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ParticiparLeilao",
			Handler:       _LeilaoService_ParticiparLeilao_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/leilao.proto",
}
