// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/leilao.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MensagemLance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	Valor         float64                `protobuf:"fixed64,2,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensagemLance) Reset() {
	*x = MensagemLance{}
	mi := &file_proto_leilao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensagemLance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensagemLance) ProtoMessage() {}

func (x *MensagemLance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensagemLance.ProtoReflect.Descriptor instead.
func (*MensagemLance) Descriptor() ([]byte, []int) {
	return file_proto_leilao_proto_rawDescGZIP(), []int{0}
}

func (x *MensagemLance) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *MensagemLance) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type AtualizacaoLeilao struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaiorLanceador string                 `protobuf:"bytes,1,opt,name=maior_lanceador,json=maiorLanceador,proto3" json:"maior_lanceador,omitempty"`
	MaiorValor     float64                `protobuf:"fixed64,2,opt,name=maior_valor,json=maiorValor,proto3" json:"maior_valor,omitempty"`
	Mensagem       string                 `protobuf:"bytes,3,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AtualizacaoLeilao) Reset() {
	*x = AtualizacaoLeilao{}
	mi := &file_proto_leilao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtualizacaoLeilao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtualizacaoLeilao) ProtoMessage() {}

func (x *AtualizacaoLeilao) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leilao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtualizacaoLeilao.ProtoReflect.Descriptor instead.
func (*AtualizacaoLeilao) Descriptor() ([]byte, []int) {
	return file_proto_leilao_proto_rawDescGZIP(), []int{1}
}

func (x *AtualizacaoLeilao) GetMaiorLanceador() string {
	if x != nil {
		return x.MaiorLanceador
	}
	return ""
}

func (x *AtualizacaoLeilao) GetMaiorValor() float64 {
	if x != nil {
		return x.MaiorValor
	}
	return 0
}

func (x *AtualizacaoLeilao) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

var File_proto_leilao_proto protoreflect.FileDescriptor

const file_proto_leilao_proto_rawDesc = "" +
	"\n" +
	"\x12proto/leilao.proto\x12\x06leilao\"D\n" +
	"\rMensagemLance\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\x01R\x05valor\"y\n" +
	"\x11AtualizacaoLeilao\x12'\n" +
	"\x0fmaior_lanceador\x18\x01 \x01(\tR\x0emaiorLanceador\x12\x1f\n" +
	"\vmaior_valor\x18\x02 \x01(\x01R\n" +
	"maiorValor\x12\x1a\n" +
	"\bmensagem\x18\x03 \x01(\tR\bmensagem2Y\n" +
	"\rLeilaoService\x12H\n" +
	"\x10ParticiparLeilao\x12\x15.leilao.MensagemLance\x1a\x19.leilao.AtualizacaoLeilao(\x010\x01B\x16Z\x14grpc-leilao-go/protob\x06proto3"

var (
	file_proto_leilao_proto_rawDescOnce sync.Once
	file_proto_leilao_proto_rawDescData []byte
)

func file_proto_leilao_proto_rawDescGZIP() []byte {
	file_proto_leilao_proto_rawDescOnce.Do(func() {
		file_proto_leilao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_leilao_proto_rawDesc), len(file_proto_leilao_proto_rawDesc)))
	})
	return file_proto_leilao_proto_rawDescData
}

var file_proto_leilao_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_leilao_proto_goTypes = []any{
	(*MensagemLance)(nil),     // 0: leilao.MensagemLance
	(*AtualizacaoLeilao)(nil), // 1: leilao.AtualizacaoLeilao
}
var file_proto_leilao_proto_depIdxs = []int32{
	0, // 0: leilao.LeilaoService.ParticiparLeilao:input_type -> leilao.MensagemLance
	1, // 1: leilao.LeilaoService.ParticiparLeilao:output_type -> leilao.AtualizacaoLeilao
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_leilao_proto_init() }
func file_proto_leilao_proto_init() {
	if File_proto_leilao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_leilao_proto_rawDesc), len(file_proto_leilao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leilao_proto_goTypes,
		DependencyIndexes: file_proto_leilao_proto_depIdxs,
		MessageInfos:      file_proto_leilao_proto_msgTypes,
	}.Build()
	File_proto_leilao_proto = out.File
	file_proto_leilao_proto_goTypes = nil
	file_proto_leilao_proto_depIdxs = nil
}
